### ISSUE TITLE
does not work. 

### ISSUE THREAD

**Issue by fre2mansur** [tommusrhodus/HTML-Page-Builder#7]
I just downloaded and browsed the index  file i could not drag drop the contents

in my console log
XML Parsing Error: mismatched tag. Expected: </input>.
Location: file:///D:/workplace/lab/builder/HTML-Page-Builder-master/blocks/navbar-block.html
Line Number 36, Column 12:

**Comment by tommusrhodus** [comment]
This is an abandoned project and extremely far from complete. Expect issues at every turn if you choose to continue to build on top of this.
